# -*- coding: utf-8 -*-
"""Email Scraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SYZwaIrD8GWtIx9STZr0c7vVCFzVMRsN

**Set-Up**
"""

#Filter setting coming soon !

"""**Imports**"""

from urllib.request import urlopen

"""Pick url"""

url = "https://pastebin.pl/view/2fee45a4"
page = urlopen(url)
page

"""Show Html Content"""

html_bytes = page.read()
try:
  html = html_bytes.decode("utf-8")
except UnicodeDecodeError:
  html = html_bytes.decode("cp1252")
if html == "":
  print("Decoding failed.")
  exit()
print(html)

"""Extract emails"""

import re
line = html
match = re.findall(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', line)
for i in match:
    print(i)